-- Migration 0001: languages, users, auth, RBAC, security events, audit log
--
-- Conventions for all migrations
--   * STRICT tables (SQLite type enforcement).
--   * Primary keys are TEXT ids generated by the application (UUID) unless the
--     table is a singleton (id = 1) or keyed by natural composite keys.
--   * Timestamps: TEXT ISO-8601 UTC, e.g. 2026-09-30T05:00:00.000Z.
--   * Calendar dates (stay dates): TEXT YYYY-MM-DD in Asia/Bangkok business time.
--   * Money: INTEGER satang (1 THB = 100 satang). Never REAL.
--   * Booleans: INTEGER 0/1 with CHECK.
--   * D1 enforces foreign keys. No ON DELETE CASCADE on business records.

-- ---------------------------------------------------------------------------
-- Languages (data-driven; no language list hard-coded in SQL constraints)
-- ---------------------------------------------------------------------------
CREATE TABLE languages (
  code        TEXT PRIMARY KEY,                     -- BCP-47: th, en, zh-CN
  path        TEXT NOT NULL UNIQUE,                 -- URL segment: th, en, zh-cn
  native_name TEXT NOT NULL,
  is_default  INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  is_enabled  INTEGER NOT NULL DEFAULT 1 CHECK (is_enabled IN (0, 1)),
  sort_order  INTEGER NOT NULL DEFAULT 0
) STRICT;

CREATE UNIQUE INDEX ux_languages_single_default ON languages (is_default) WHERE is_default = 1;

INSERT INTO languages (code, path, native_name, is_default, is_enabled, sort_order) VALUES
  ('th', 'th', 'ไทย', 1, 1, 1),
  ('en', 'en', 'English', 0, 1, 2),
  ('zh-CN', 'zh-cn', '简体中文', 0, 1, 3);

-- ---------------------------------------------------------------------------
-- Users (soft delete: status = DELETED + deleted_at/deleted_by)
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id                   TEXT PRIMARY KEY,
  email                TEXT NOT NULL COLLATE NOCASE UNIQUE,
  username             TEXT COLLATE NOCASE UNIQUE,
  display_name         TEXT NOT NULL,
  password_hash        TEXT NOT NULL,              -- PHC string, never plain text
  password_changed_at  TEXT,
  must_change_password INTEGER NOT NULL DEFAULT 0 CHECK (must_change_password IN (0, 1)),
  preferred_language   TEXT REFERENCES languages (code),
  status               TEXT NOT NULL DEFAULT 'ACTIVE'
                       CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DELETED')),
  failed_login_count   INTEGER NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0),
  locked_until         TEXT,
  last_login_at        TEXT,
  created_by           TEXT REFERENCES users (id),
  created_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at           TEXT,
  deleted_by           TEXT REFERENCES users (id),
  CHECK ((status = 'DELETED') = (deleted_at IS NOT NULL)),
  CHECK (length(email) BETWEEN 3 AND 254 AND email LIKE '%_@_%'),
  CHECK (password_hash <> '')
) STRICT;

CREATE INDEX ix_users_status ON users (status);

-- ---------------------------------------------------------------------------
-- RBAC
-- ---------------------------------------------------------------------------
CREATE TABLE roles (
  id         TEXT PRIMARY KEY,
  code       TEXT NOT NULL UNIQUE,                   -- SUPER_ADMIN, MANAGER, …
  is_system  INTEGER NOT NULL DEFAULT 0 CHECK (is_system IN (0, 1)),
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

CREATE TABLE role_translations (
  role_id       TEXT NOT NULL REFERENCES roles (id),
  language_code TEXT NOT NULL REFERENCES languages (code),
  name          TEXT NOT NULL,
  description   TEXT,
  PRIMARY KEY (role_id, language_code)
) STRICT;

CREATE TABLE permissions (
  id          TEXT PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,                  -- users.delete, bookings.view, …
  module      TEXT NOT NULL,
  description TEXT NOT NULL,
  CHECK (code GLOB '[a-z]*.[a-z]*')
) STRICT;

CREATE TABLE role_permissions (
  role_id       TEXT NOT NULL REFERENCES roles (id),
  permission_id TEXT NOT NULL REFERENCES permissions (id),
  PRIMARY KEY (role_id, permission_id)
) STRICT;

CREATE TABLE user_roles (
  user_id    TEXT NOT NULL REFERENCES users (id),
  role_id    TEXT NOT NULL REFERENCES roles (id),
  granted_by TEXT REFERENCES users (id),
  granted_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  PRIMARY KEY (user_id, role_id)
) STRICT;

CREATE INDEX ix_user_roles_role ON user_roles (role_id);

-- Per-user overrides on top of role permissions. DENY wins over GRANT.
CREATE TABLE user_permissions (
  user_id       TEXT NOT NULL REFERENCES users (id),
  permission_id TEXT NOT NULL REFERENCES permissions (id),
  effect        TEXT NOT NULL CHECK (effect IN ('GRANT', 'DENY')),
  granted_by    TEXT REFERENCES users (id),
  granted_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  PRIMARY KEY (user_id, permission_id)
) STRICT;

-- ---------------------------------------------------------------------------
-- Sessions & password reset (only hashes of tokens are stored)
-- ---------------------------------------------------------------------------
CREATE TABLE sessions (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES users (id),
  token_hash    TEXT NOT NULL UNIQUE,                -- SHA-256 hex of the cookie token
  remember_me   INTEGER NOT NULL DEFAULT 0 CHECK (remember_me IN (0, 1)),
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  last_seen_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  expires_at    TEXT NOT NULL,
  rotated_from  TEXT REFERENCES sessions (id),
  revoked_at    TEXT,
  revoke_reason TEXT CHECK (revoke_reason IN ('LOGOUT', 'ROTATED', 'FORCE_LOGOUT', 'PASSWORD_CHANGED',
                                              'USER_SUSPENDED', 'USER_DELETED', 'EXPIRED', 'SECURITY')),
  ip            TEXT,
  user_agent    TEXT,
  CHECK ((revoked_at IS NULL) = (revoke_reason IS NULL))
) STRICT;

CREATE INDEX ix_sessions_user_active ON sessions (user_id) WHERE revoked_at IS NULL;
CREATE INDEX ix_sessions_expires ON sessions (expires_at);

CREATE TABLE password_reset_tokens (
  id           TEXT PRIMARY KEY,
  user_id      TEXT NOT NULL REFERENCES users (id),
  token_hash   TEXT NOT NULL UNIQUE,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  expires_at   TEXT NOT NULL,
  used_at      TEXT,
  requested_ip TEXT
) STRICT;

CREATE INDEX ix_password_reset_tokens_user ON password_reset_tokens (user_id);

-- ---------------------------------------------------------------------------
-- Security events (login failures, lockouts, permission denials, …)
-- ---------------------------------------------------------------------------
CREATE TABLE security_events (
  id           TEXT PRIMARY KEY,
  event_type   TEXT NOT NULL,        -- LOGIN_SUCCESS, LOGIN_FAILED, ACCOUNT_LOCKED, PERMISSION_DENIED, …
  severity     TEXT NOT NULL DEFAULT 'INFO' CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
  user_id      TEXT REFERENCES users (id),
  identifier   TEXT,                 -- attempted email/username (never a password)
  ip           TEXT,
  user_agent   TEXT,
  details_json TEXT CHECK (details_json IS NULL OR json_valid(details_json)),
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

CREATE INDEX ix_security_events_created ON security_events (created_at);
CREATE INDEX ix_security_events_type ON security_events (event_type, created_at);
CREATE INDEX ix_security_events_user ON security_events (user_id, created_at);
CREATE INDEX ix_security_events_ip ON security_events (ip, created_at);

-- ---------------------------------------------------------------------------
-- Audit log (append-only; passwords, tokens and secrets must never be written)
-- ---------------------------------------------------------------------------
CREATE TABLE audit_logs (
  id         TEXT PRIMARY KEY,
  user_id    TEXT REFERENCES users (id),
  action     TEXT NOT NULL,          -- CREATE, UPDATE, DELETE, RESTORE, PUBLISH, VERIFY, …
  module     TEXT NOT NULL,          -- bookings, pricing, users, theme, …
  record_id  TEXT,
  old_value  TEXT CHECK (old_value IS NULL OR json_valid(old_value)),
  new_value  TEXT CHECK (new_value IS NULL OR json_valid(new_value)),
  ip         TEXT,
  user_agent TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

CREATE INDEX ix_audit_logs_created ON audit_logs (created_at);
CREATE INDEX ix_audit_logs_module_record ON audit_logs (module, record_id);
CREATE INDEX ix_audit_logs_user ON audit_logs (user_id, created_at);

CREATE TRIGGER trg_audit_logs_no_update BEFORE UPDATE ON audit_logs
BEGIN
  SELECT RAISE(ABORT, 'AUDIT_LOG_IMMUTABLE');
END;

CREATE TRIGGER trg_audit_logs_no_delete BEFORE DELETE ON audit_logs
BEGIN
  SELECT RAISE(ABORT, 'AUDIT_LOG_IMMUTABLE');
END;

-- ---------------------------------------------------------------------------
-- SUPER_ADMIN safety net (spec §33). The service layer checks first and returns
-- a friendly error; these triggers make the rule impossible to bypass.
-- "Active super admin" = ACTIVE user holding the SUPER_ADMIN role.
-- ---------------------------------------------------------------------------
CREATE TRIGGER trg_keep_last_super_admin_role BEFORE DELETE ON user_roles
WHEN OLD.role_id = (SELECT id FROM roles WHERE code = 'SUPER_ADMIN')
 AND (SELECT status FROM users WHERE id = OLD.user_id) = 'ACTIVE'
 AND (SELECT COUNT(*) FROM user_roles ur JOIN users u ON u.id = ur.user_id
       WHERE ur.role_id = OLD.role_id AND u.status = 'ACTIVE' AND ur.user_id <> OLD.user_id) = 0
BEGIN
  SELECT RAISE(ABORT, 'LAST_SUPER_ADMIN');
END;

CREATE TRIGGER trg_keep_last_super_admin_status BEFORE UPDATE OF status ON users
WHEN OLD.status = 'ACTIVE' AND NEW.status <> 'ACTIVE'
 AND EXISTS (SELECT 1 FROM user_roles ur JOIN roles r ON r.id = ur.role_id
              WHERE ur.user_id = OLD.id AND r.code = 'SUPER_ADMIN')
 AND (SELECT COUNT(*) FROM user_roles ur JOIN roles r ON r.id = ur.role_id JOIN users u ON u.id = ur.user_id
       WHERE r.code = 'SUPER_ADMIN' AND u.status = 'ACTIVE' AND u.id <> OLD.id) = 0
BEGIN
  SELECT RAISE(ABORT, 'LAST_SUPER_ADMIN');
END;

-- Users are never hard-deleted by the application (soft delete). Block it at DB level too.
CREATE TRIGGER trg_users_no_hard_delete BEFORE DELETE ON users
BEGIN
  SELECT RAISE(ABORT, 'USER_HARD_DELETE_FORBIDDEN');
END;
